"""Initial migration

Revision ID: 05cc405bcd62
Revises: 
Create Date: 2024-08-12 15:47:58.791189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05cc405bcd62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completed_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home', sa.String(length=100), nullable=True),
    sa.Column('away', sa.String(length=100), nullable=True),
    sa.Column('home_win_probability', sa.Float(), nullable=True),
    sa.Column('draw_probability', sa.Float(), nullable=True),
    sa.Column('away_win_probability', sa.Float(), nullable=True),
    sa.Column('team_to_win_prediction', sa.Integer(), nullable=True),
    sa.Column('average_goals_prediction', sa.Float(), nullable=True),
    sa.Column('weather_in_degrees', sa.String(length=50), nullable=True),
    sa.Column('odds', sa.Float(), nullable=True),
    sa.Column('full_time_score', sa.String(length=50), nullable=True),
    sa.Column('score_at_halftime', sa.String(length=50), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('time', sa.String(length=50), nullable=True),
    sa.Column('home_team_score_prediction', sa.Integer(), nullable=True),
    sa.Column('away_team_score_prediction', sa.Integer(), nullable=True),
    sa.Column('home_team_full_time_score', sa.Integer(), nullable=True),
    sa.Column('away_team_full_time_score', sa.Integer(), nullable=True),
    sa.Column('home_team_halftime_score', sa.Integer(), nullable=True),
    sa.Column('away_team_halftime_score', sa.Integer(), nullable=True),
    sa.Column('prediction_result', sa.String(length=50), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('weekly_round', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('current_week_league_standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pos', sa.Integer(), nullable=True),
    sa.Column('team', sa.Integer(), nullable=True),
    sa.Column('pld', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('draws', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('gf', sa.Integer(), nullable=True),
    sa.Column('ga', sa.Integer(), nullable=True),
    sa.Column('ppg_last_5_matches', sa.Float(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('previous_week_league_standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pos', sa.Integer(), nullable=True),
    sa.Column('team', sa.Integer(), nullable=True),
    sa.Column('pld', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('draws', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('gf', sa.Integer(), nullable=True),
    sa.Column('ga', sa.Integer(), nullable=True),
    sa.Column('ppg_last_5_matches', sa.Float(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upcoming_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home', sa.Integer(), nullable=True),
    sa.Column('away', sa.Integer(), nullable=True),
    sa.Column('home_win_probability', sa.Float(), nullable=True),
    sa.Column('draw_probability', sa.Float(), nullable=True),
    sa.Column('away_win_probability', sa.Float(), nullable=True),
    sa.Column('team_to_win_prediction', sa.Integer(), nullable=True),
    sa.Column('scoreline_prediction', sa.String(length=100), nullable=True),
    sa.Column('average_goals_prediction', sa.Float(), nullable=True),
    sa.Column('weather_in_degrees', sa.String(length=50), nullable=True),
    sa.Column('odds', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('home_team_score_prediction', sa.Integer(), nullable=True),
    sa.Column('away_team_score_prediction', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('weekly_round', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('testing_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('scoreline_prediction', sa.String(length=100), nullable=True))
        batch_op.alter_column('home',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('away',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('home_win_probability',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('draw_probability',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('away_win_probability',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('team_to_win_prediction',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('average_goals_prediction',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('weather_in_degrees',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('odds',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('date',
               existing_type=mysql.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('time',
               existing_type=mysql.TEXT(),
               type_=sa.Time(),
               existing_nullable=True)
        batch_op.alter_column('home_team_score_prediction',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('away_team_score_prediction',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('day_of_week',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('month',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('weekly_round',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('home_team_pos',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('home_team_matches_played',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('home_team_wins',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('home_team_draws',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('home_team_losses',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('home_team_gf',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('home_team_ga',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('home_team_ppg_last_5_matches',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('home_team_points',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('away_team_pos',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('away_team_matches_played',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('away_team_wins',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('away_team_draws',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('away_team_losses',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('away_team_gf',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('away_team_ga',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('away_team_ppg_last_5_matches',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('away_team_points',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('away_team_halftime_score')
        batch_op.drop_column('away_team_full_time_score')
        batch_op.drop_column('prediction_result')
        batch_op.drop_column('score_at_halftime')
        batch_op.drop_column('full_time_score')
        batch_op.drop_column('home_team_halftime_score')
        batch_op.drop_column('home_team_full_time_score')

    with op.batch_alter_table('training_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('home_win_probability',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('draw_probability',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('away_win_probability',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('average_goals_prediction',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('weather_in_degrees',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('odds',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('full_time_score',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('score_at_halftime',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('home_team_ppg_last_5_matches',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('away_team_ppg_last_5_matches',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_data', schema=None) as batch_op:
        batch_op.alter_column('away_team_ppg_last_5_matches',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('home_team_ppg_last_5_matches',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('score_at_halftime',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('full_time_score',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('odds',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('weather_in_degrees',
               existing_type=sa.String(length=50),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('average_goals_prediction',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('away_win_probability',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('draw_probability',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('home_win_probability',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.drop_column('id')

    with op.batch_alter_table('testing_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_team_full_time_score', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('home_team_halftime_score', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('full_time_score', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('score_at_halftime', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('prediction_result', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('away_team_full_time_score', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('away_team_halftime_score', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.alter_column('away_team_points',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('away_team_ppg_last_5_matches',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('away_team_ga',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('away_team_gf',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('away_team_losses',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('away_team_draws',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('away_team_wins',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('away_team_matches_played',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('away_team_pos',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('home_team_points',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('home_team_ppg_last_5_matches',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('home_team_ga',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('home_team_gf',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('home_team_losses',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('home_team_draws',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('home_team_wins',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('home_team_matches_played',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('home_team_pos',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('weekly_round',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('month',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('day_of_week',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('away_team_score_prediction',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('home_team_score_prediction',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('time',
               existing_type=sa.Time(),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('odds',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('weather_in_degrees',
               existing_type=sa.String(length=50),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('average_goals_prediction',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('team_to_win_prediction',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('away_win_probability',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('draw_probability',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('home_win_probability',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('away',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('home',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
        batch_op.drop_column('scoreline_prediction')
        batch_op.drop_column('id')

    op.drop_table('upcoming_matches')
    op.drop_table('previous_week_league_standings')
    op.drop_table('current_week_league_standings')
    op.drop_table('completed_matches')
    # ### end Alembic commands ###
