"""Dropped Training and Testing tables

Revision ID: 2eefcb75ae34
Revises: 05cc405bcd62
Create Date: 2024-08-12 19:32:13.123828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eefcb75ae34'
down_revision = '05cc405bcd62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testing_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home', sa.Integer(), nullable=True),
    sa.Column('away', sa.Integer(), nullable=True),
    sa.Column('home_win_probability', sa.Float(), nullable=True),
    sa.Column('draw_probability', sa.Float(), nullable=True),
    sa.Column('away_win_probability', sa.Float(), nullable=True),
    sa.Column('team_to_win_prediction', sa.Integer(), nullable=True),
    sa.Column('scoreline_prediction', sa.String(length=100), nullable=True),
    sa.Column('average_goals_prediction', sa.Float(), nullable=True),
    sa.Column('weather_in_degrees', sa.String(length=50), nullable=True),
    sa.Column('odds', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('home_team_score_prediction', sa.Integer(), nullable=True),
    sa.Column('away_team_score_prediction', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('weekly_round', sa.Integer(), nullable=True),
    sa.Column('home_team_pos', sa.Integer(), nullable=True),
    sa.Column('home_team_matches_played', sa.Integer(), nullable=True),
    sa.Column('home_team_wins', sa.Integer(), nullable=True),
    sa.Column('home_team_draws', sa.Integer(), nullable=True),
    sa.Column('home_team_losses', sa.Integer(), nullable=True),
    sa.Column('home_team_gf', sa.Integer(), nullable=True),
    sa.Column('home_team_ga', sa.Integer(), nullable=True),
    sa.Column('home_team_ppg_last_5_matches', sa.Float(), nullable=True),
    sa.Column('home_team_points', sa.Integer(), nullable=True),
    sa.Column('away_team_pos', sa.Integer(), nullable=True),
    sa.Column('away_team_matches_played', sa.Integer(), nullable=True),
    sa.Column('away_team_wins', sa.Integer(), nullable=True),
    sa.Column('away_team_draws', sa.Integer(), nullable=True),
    sa.Column('away_team_losses', sa.Integer(), nullable=True),
    sa.Column('away_team_gf', sa.Integer(), nullable=True),
    sa.Column('away_team_ga', sa.Integer(), nullable=True),
    sa.Column('away_team_ppg_last_5_matches', sa.Float(), nullable=True),
    sa.Column('away_team_points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home', sa.Integer(), nullable=True),
    sa.Column('away', sa.Integer(), nullable=True),
    sa.Column('home_win_probability', sa.Float(), nullable=True),
    sa.Column('draw_probability', sa.Float(), nullable=True),
    sa.Column('away_win_probability', sa.Float(), nullable=True),
    sa.Column('team_to_win_prediction', sa.Integer(), nullable=True),
    sa.Column('average_goals_prediction', sa.Float(), nullable=True),
    sa.Column('weather_in_degrees', sa.String(length=50), nullable=True),
    sa.Column('odds', sa.Float(), nullable=True),
    sa.Column('full_time_score', sa.String(length=100), nullable=True),
    sa.Column('score_at_halftime', sa.String(length=100), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('home_team_score_prediction', sa.Integer(), nullable=True),
    sa.Column('away_team_score_prediction', sa.Integer(), nullable=True),
    sa.Column('home_team_full_time_score', sa.Integer(), nullable=True),
    sa.Column('away_team_full_time_score', sa.Integer(), nullable=True),
    sa.Column('home_team_halftime_score', sa.Integer(), nullable=True),
    sa.Column('away_team_halftime_score', sa.Integer(), nullable=True),
    sa.Column('prediction_result', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('weekly_round', sa.Integer(), nullable=True),
    sa.Column('home_team_pos', sa.Integer(), nullable=True),
    sa.Column('home_team_matches_played', sa.Integer(), nullable=True),
    sa.Column('home_team_wins', sa.Integer(), nullable=True),
    sa.Column('home_team_draws', sa.Integer(), nullable=True),
    sa.Column('home_team_losses', sa.Integer(), nullable=True),
    sa.Column('home_team_gf', sa.Integer(), nullable=True),
    sa.Column('home_team_ga', sa.Integer(), nullable=True),
    sa.Column('home_team_ppg_last_5_matches', sa.Float(), nullable=True),
    sa.Column('home_team_points', sa.Integer(), nullable=True),
    sa.Column('away_team_pos', sa.Integer(), nullable=True),
    sa.Column('away_team_matches_played', sa.Integer(), nullable=True),
    sa.Column('away_team_wins', sa.Integer(), nullable=True),
    sa.Column('away_team_draws', sa.Integer(), nullable=True),
    sa.Column('away_team_losses', sa.Integer(), nullable=True),
    sa.Column('away_team_gf', sa.Integer(), nullable=True),
    sa.Column('away_team_ga', sa.Integer(), nullable=True),
    sa.Column('away_team_ppg_last_5_matches', sa.Float(), nullable=True),
    sa.Column('away_team_points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_data')
    op.drop_table('testing_data')
    # ### end Alembic commands ###
